services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_db
    ports:
      - 13306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/init:/docker-entrypoint-initdb.d