services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_db
    ports:
      - 13306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 16379:6379

  recommend-service:
    image: fos-recommend-service:0.0.1-SNAPSHOT
    ports:
      - 18080:18080
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test_db
      - SPRING_DATASOURCE_USERNAME=test_user
      - SPRING_DATASOURCE_PASSWORD=test_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
