
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql

  datasource:
    url: jdbc:mysql://127.0.0.1:13306/test_db
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver